[project]
name = "cv-observer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.0.20",
    "dotenv>=0.9.9",
    "mistralai>=1.9.7",
    "openai>=1.101.0",
    "openai-agents>=0.2.9",
]
